#!/bin/bash
# Gallery Image Upload Organizer for Muts Safaris
# Run this script from the images/gallery/ directory

echo "🖼️  Muts Safaris Gallery Image Organizer"
echo "=========================================="
echo ""

# Create subdirectories if they don't exist
echo "📁 Creating gallery subdirectories..."
mkdir -p wildlife landscapes guests accommodations

echo ""
echo "📋 GALLERY IMAGE UPLOAD GUIDE"
echo "=============================="
echo ""
echo "Upload your images to these specific locations:"
echo ""
echo "🏞️  WILDLIFE GALLERY (images/gallery/wildlife/):"
echo "   - lion-sunset.jpg (Lion pride at sunset)"
echo "   - leopard-tree.jpg (Leopard in acacia tree)"
echo "   - elephant-family.jpg (Elephant family herd)"
echo "   - buffalo-herd.jpg (Cape buffalo herd)"
echo "   - rhino-dust.jpg (Black rhino in dust)"
echo "   - cheetah-hunt.jpg (Cheetah hunting)"
echo "   - wildebeest-river.jpg (Wildebeest river crossing)"
echo "   - zebra-plains.jpg (Zebra on plains)"
echo "   - crocodile-ambush.jpg (Nile crocodile)"
echo "   - flamingo-lake.jpg (Lesser flamingos at lake)"
echo "   - secretary-bird.jpg (Secretary bird)"
echo "   - fish-eagle.jpg (African fish eagle)"
echo "   - giraffe-neck.jpg (Giraffe silhouette)"
echo "   - hippo-pool.jpg (Hippo in water)"
echo "   - impala-group.jpg (Impala herd)"
echo "   - hyena-laugh.jpg (Spotted hyena)"
echo "   - warthog-family.jpg (Warthog family)"
echo "   - monkey-troop.jpg (Baboon troop)"
echo ""
echo "🌄 LANDSCAPES GALLERY (images/gallery/landscapes/):"
echo "   - maasai-mara-plains.jpg (Maasai Mara grasslands)"
echo "   - amboseli-elephants.jpg (Amboseli with Kilimanjaro)"
echo "   - tsavo-dust.jpg (Tsavo red earth)"
echo "   - lake-nakuru-flamingos.jpg (Lake Nakuru flamingos)"
echo "   - mount-kenya.jpg (Mount Kenya peaks)"
echo "   - samburu-landscape.jpg (Samburu desert)"
echo "   - nairobi-national-park.jpg (Nairobi city + wildlife)"
echo "   - hells-gate-canyon.jpg (Hell's Gate gorge)"
echo ""
echo "👥 GUEST EXPERIENCES (images/gallery/guests/):"
echo "   - family-safari.jpg (Family on safari)"
echo "   - hot-air-balloon.jpg (Hot air balloon safari)"
echo "   - maasai-dance.jpg (Maasai cultural dance)"
echo "   - camel-ride.jpg (Camel safari)"
echo "   - lion-cub.jpg (Guest with lion cub)"
echo "   - sunset-cocktail.jpg (Sundowner drinks)"
echo "   - cooking-class.jpg (Maasai cooking lesson)"
echo "   - village-visit.jpg (Maasai village visit)"
echo ""
echo "🏨 ACCOMMODATIONS (images/gallery/accommodations/):"
echo "   - luxury-tent.jpg (Luxury safari tent)"
echo "   - pool-sunset.jpg (Lodge pool at sunset)"
echo "   - dining-room.jpg (Restaurant interior)"
echo "   - bedroom-suite.jpg (Luxury bedroom)"
echo "   - lounge-area.jpg (Common lounge)"
echo "   - outdoor-shower.jpg (Outdoor bathroom)"
echo "   - fire-pit.jpg (Evening campfire)"
echo "   - spa-treatment.jpg (Spa facility)"
echo ""
echo "📐 IMAGE SPECIFICATIONS:"
echo "   - Dimensions: 600x400px minimum (3:2 aspect ratio)"
echo "   - Format: JPEG preferred"
echo "   - Size: < 200KB per image"
echo "   - CSS will automatically constrain to 600x400px max"
echo ""
echo "🔄 UPLOAD PROCESS:"
echo "   1. Upload images to correct subdirectories"
echo "   2. Use exact filenames listed above"
echo "   3. Refresh gallery pages to see changes"
echo "   4. Images display in responsive grids automatically"
echo ""
echo "✅ CURRENT STATUS:"
echo "   Directories created: ✓"
echo "   Placeholder images: Added for testing"
echo "   Gallery pages: Ready to display"
echo ""
echo "🌐 TEST YOUR GALLERY:"
echo "   Main Gallery: http://localhost:8000/pages/gallery/index.html"
echo "   Wildlife: http://localhost:8000/pages/gallery/wildlife/index.html"
echo ""
echo "Ready for image uploads! 📸"